package com.qxtao.viewanalysis.constant

object Constant {
    const val ACTION_HIERARCHY_VIEW = "ACTION_HIERARCHY_VIEW"
    const val ACTION_SET_FLOAT_BUTTON_VISIBLE = "ACTION_SET_FLOAT_BUTTON_VISIBLE"
    const val ACTION_FINISH_HIERARCHY_ACTIVITY = "ACTION_FINISH_HIERARCHY_ACTIVITY"
    const val ACTION_FINISH_MAIN_ACTIVITY = "ACTION_FINISH_MAIN_ACTIVITY"
    const val ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED = "ACTION_ACCESSIBILITY_SERVICE_STATUS_CHANGED"
    const val ACTION_SEND_CURRENT_ACTIVITY = "ACTION_SEND_CURRENT_ACTIVITY"
    const val USE_ROOT = "USE_ROOT"
}